services:
  postgres:
    image: postgres:15
    container_name: cinema_postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: mongodb_cinema
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: cinema_mqtt
    restart: always
    env_file:
      - ./.env
    environment:
      - MQTT_BROKER_CLIENT_ID=${MQTT_BROKER_CLIENT_ID}
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - cinema_network
    volumes:
      - mqtt_data:/mosquitto/data
      - ./mosquitto-config:/mosquitto/config
      - mqtt_log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'health check' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: ./backend-cinema/Dockerfile
    container_name: cinema_backend
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=postgres
      - DATABASE_URL=mongodb://admin:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/cinema_db?authSource=admin
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - RUN_SEEDER=true
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - backend_data:/app/data


volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  mqtt_data:
    driver: local
  mqtt_config:
    driver: local
  mqtt_log:
    driver: local
  backend_data:
    driver: local

networks:
  cinema_network:
    driver: bridge