"""Fixed alembic env

Revision ID: 348255a893d5
Revises: 0c8773ebe62b
Create Date: 2025-07-22 21:24:04.069235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348255a893d5'
down_revision: Union[str, Sequence[str], None] = '0c8773ebe62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('sessoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filme_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('preco_por_veiculo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
