"""Corrige tipos de data e hora

Revision ID: 79e61e121bcf
Revises: fa7b11936659
Create Date: 2025-07-22 16:07:35.264143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e61e121bcf'
down_revision: Union[str, Sequence[str], None] = 'fa7b11936659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('placa', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clientes_pkey'))
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_table('sessoes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filme_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('hora', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('preco_por_veiculo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sessoes_pkey'))
    )
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    # ### end Alembic commands ###
