from enum import Enum

class GeneroEnum(str, Enum):
    ACAO = "Ação"
    AVENTURA = "Aventura"
    ANIMACAO = "Animação"
    ANIME = "Anime"
    BIOGRAFIA = "Biografia"
    COMEDIA = "Comédia"
    DANCA = "Dança"
    DOCUMENTARIO = "Documentário"
    DRAMA = "Drama"
    ESPIONAGEM = "Espionagem"
    FAROESTE = "Faroeste"
    FANTASIA = "Fantasia"
    FICCAO_CIENTIFICA = "Ficção científica"
    MUSICAL = "Musical"
    FILME_POLICIAL = "Filme policial"
    TERROR = "Terror"
    ROMANCE = "Romance"
    SUSPENSE = "Suspense"