"""Correcting movie attributes

Revision ID: 00d12dbc6ca4
Revises: 7bae2c8ed1f3
Create Date: 2025-07-24 11:59:45.235812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00d12dbc6ca4'
down_revision: Union[str, Sequence[str], None] = '7bae2c8ed1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar o tipo enum primeiro
    classificacao_enum = sa.Enum('LIVRE', 'DEZ_ANOS', 'DOZE_ANOS', 'QUATORZE_ANOS', 'DEZESSEIS_ANOS', 'DEZOITO_ANOS', name='classificacaoindicativaenum')
    classificacao_enum.create(op.get_bind())
    
    # Adicionar a coluna com o enum
    op.add_column('filmes', sa.Column('classificacao_indicativa', classificacao_enum, nullable=False))
    
    # Alterar a coluna de gêneros e remover a nota
    op.alter_column('filmes', 'generos',
               existing_type=postgresql.ARRAY(postgresql.ENUM('ACAO', 'AVENTURA', 'ANIMACAO', 'ANIME', 'BIOGRAFIA', 'COMEDIA', 'DANCA', 'DOCUMENTARIO', 'DRAMA', 'ESPIONAGEM', 'FAROESTE', 'FANTASIA', 'FICCAO_CIENTIFICA', 'MUSICAL', 'FILME_POLICIAL', 'TERROR', 'ROMANCE', 'SUSPENSE', name='generoenum')),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False)
    op.drop_column('filmes', 'nota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filmes', sa.Column('nota', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('filmes', 'generos',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(postgresql.ENUM('ACAO', 'AVENTURA', 'ANIMACAO', 'ANIME', 'BIOGRAFIA', 'COMEDIA', 'DANCA', 'DOCUMENTARIO', 'DRAMA', 'ESPIONAGEM', 'FAROESTE', 'FANTASIA', 'FICCAO_CIENTIFICA', 'MUSICAL', 'FILME_POLICIAL', 'TERROR', 'ROMANCE', 'SUSPENSE', name='generoenum')),
               existing_nullable=False)
    op.drop_column('filmes', 'classificacao_indicativa')
    
    # Remover o tipo enum
    sa.Enum(name='classificacaoindicativaenum').drop(op.get_bind())
    # ### end Alembic commands ###
