"""Base migration

Revision ID: 7bae2c8ed1f3
Revises: 
Create Date: 2025-07-22 23:20:40.794579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7bae2c8ed1f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type if it doesn't exist (PostgreSQL compatible way)
    conn = op.get_bind()
    
    # Check if the enum type already exists
    result = conn.execute(sa.text("""
        SELECT 1 FROM pg_type WHERE typname = 'generoenum'
    """)).fetchone()
    
    # Create enum only if it doesn't exist
    if not result:
        conn.execute(sa.text("""
            CREATE TYPE generoenum AS ENUM ('ACAO', 'AVENTURA', 'ANIMACAO', 'ANIME', 'BIOGRAFIA', 'COMEDIA', 'DANCA', 'DOCUMENTARIO', 'DRAMA', 'ESPIONAGEM', 'FAROESTE', 'FANTASIA', 'FICCAO_CIENTIFICA', 'MUSICAL', 'FILME_POLICIAL', 'TERROR', 'ROMANCE', 'SUSPENSE')
        """))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('filmes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('diretor', sa.String(length=100), nullable=False),
    sa.Column('generos', sa.ARRAY(postgresql.ENUM('ACAO', 'AVENTURA', 'ANIMACAO', 'ANIME', 'BIOGRAFIA', 'COMEDIA', 'DANCA', 'DOCUMENTARIO', 'DRAMA', 'ESPIONAGEM', 'FAROESTE', 'FANTASIA', 'FICCAO_CIENTIFICA', 'MUSICAL', 'FILME_POLICIAL', 'TERROR', 'ROMANCE', 'SUSPENSE', name='generoenum', create_type=False)), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filmes_id'), 'filmes', ['id'], unique=False)
    op.create_table('sessoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filme_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('preco_por_veiculo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_filmes_id'), table_name='filmes')
    op.drop_table('filmes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
