from enum import Enum

class ConfigName(str, Enum):

    APP_PORT = "APP_PORT"
    
    # PostgreSQL
    POSTGRES_HOST = "POSTGRES_HOST"
    POSTGRES_PORT = "POSTGRES_PORT"
    POSTGRES_DATABASE = "POSTGRES_DATABASE"
    POSTGRES_USER = "POSTGRES_USER"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"

    # MongoDB
    MONGODB_CONNECTION_STRING = "MONGODB_CONNECTION_STRING"
    MONGODB_DATABASE_NAME = "MONGODB_DATABASE_NAME"
    MONGODB_DATABASE_COLLECTION_NAME = "MONGODB_DATABASE_COLLECTION_NAME"

    # MQTT Broker
    MQTT_BROKER_URL = "MQTT_BROKER_URL"
    MQTT_BROKER_PORT = "MQTT_BROKER_PORT"
    MQTT_BROKER_CLIENT_ID = "MQTT_BROKER_CLIENT_ID"