from enum import Enum

class ConfigName(str, Enum):

    APP_PORT = "APP_PORT"
    
    # PostgreSQL
    POSTGRES_HOST = "POSTGRES_HOST"
    POSTGRES_PORT = "POSTGRES_PORT"
    POSTGRES_DATABASE = "POSTGRES_DATABASE"
    POSTGRES_USER = "POSTGRES_USER"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"

    # MongoDB
    MONGO_INITDB_ROOT_USERNAME = "MONGO_INITDB_ROOT_USERNAME"
    MONGO_INITDB_ROOT_PASSWORD = "MONGO_INITDB_ROOT_PASSWORD"
    MONGO_INITDB_DATABASE = "MONGO_INITDB_DATABASE"
    DATABASE_URL = "DATABASE_URL"

    # MQTT Broker
    MQTT_BROKER_HOSTNAME = "MQTT_BROKER_HOSTNAME"
    MQTT_BROKER_PORT = "MQTT_BROKER_PORT"
    MQTT_BROKER_CLIENT_ID = "MQTT_BROKER_CLIENT_ID"